/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: DepthObservation_.idl
  Source: DepthObservation_.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_DEPTHOBSERVATION__HPP
#define DDSCXX_DEPTHOBSERVATION__HPP

#include <cstdint>
#include <vector>
#include <string>

namespace unitree_sim
{
namespace msg
{
namespace dds_
{
class DepthObservation_
{
private:
 uint64_t frame_sequence_ = 0;
 double sim_time_ = 0.0;
 std::string frame_id_;
 uint32_t width_ = 0;
 uint32_t height_ = 0;
 std::string encoding_;
 float near_clip_ = 0.0f;
 float far_clip_ = 0.0f;
 std::vector<float> data_;

public:
  DepthObservation_() = default;

  explicit DepthObservation_(
    uint64_t frame_sequence,
    double sim_time,
    const std::string& frame_id,
    uint32_t width,
    uint32_t height,
    const std::string& encoding,
    float near_clip,
    float far_clip,
    const std::vector<float>& data) :
    frame_sequence_(frame_sequence),
    sim_time_(sim_time),
    frame_id_(frame_id),
    width_(width),
    height_(height),
    encoding_(encoding),
    near_clip_(near_clip),
    far_clip_(far_clip),
    data_(data) { }

  uint64_t frame_sequence() const { return this->frame_sequence_; }
  uint64_t& frame_sequence() { return this->frame_sequence_; }
  void frame_sequence(uint64_t _val_) { this->frame_sequence_ = _val_; }
  double sim_time() const { return this->sim_time_; }
  double& sim_time() { return this->sim_time_; }
  void sim_time(double _val_) { this->sim_time_ = _val_; }
  const std::string& frame_id() const { return this->frame_id_; }
  std::string& frame_id() { return this->frame_id_; }
  void frame_id(const std::string& _val_) { this->frame_id_ = _val_; }
  void frame_id(std::string&& _val_) { this->frame_id_ = _val_; }
  uint32_t width() const { return this->width_; }
  uint32_t& width() { return this->width_; }
  void width(uint32_t _val_) { this->width_ = _val_; }
  uint32_t height() const { return this->height_; }
  uint32_t& height() { return this->height_; }
  void height(uint32_t _val_) { this->height_ = _val_; }
  const std::string& encoding() const { return this->encoding_; }
  std::string& encoding() { return this->encoding_; }
  void encoding(const std::string& _val_) { this->encoding_ = _val_; }
  void encoding(std::string&& _val_) { this->encoding_ = _val_; }
  float near_clip() const { return this->near_clip_; }
  float& near_clip() { return this->near_clip_; }
  void near_clip(float _val_) { this->near_clip_ = _val_; }
  float far_clip() const { return this->far_clip_; }
  float& far_clip() { return this->far_clip_; }
  void far_clip(float _val_) { this->far_clip_ = _val_; }
  const std::vector<float>& data() const { return this->data_; }
  std::vector<float>& data() { return this->data_; }
  void data(const std::vector<float>& _val_) { this->data_ = _val_; }
  void data(std::vector<float>&& _val_) { this->data_ = _val_; }

  bool operator==(const DepthObservation_& _other) const
  {
    (void) _other;
    return frame_sequence_ == _other.frame_sequence_ &&
      sim_time_ == _other.sim_time_ &&
      frame_id_ == _other.frame_id_ &&
      width_ == _other.width_ &&
      height_ == _other.height_ &&
      encoding_ == _other.encoding_ &&
      near_clip_ == _other.near_clip_ &&
      far_clip_ == _other.far_clip_ &&
      data_ == _other.data_;
  }

  bool operator!=(const DepthObservation_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::unitree_sim::msg::dds_::DepthObservation_>::getTypeName()
{
  return "unitree_sim::msg::dds_::DepthObservation_";
}

template <> constexpr bool TopicTraits<::unitree_sim::msg::dds_::DepthObservation_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::unitree_sim::msg::dds_::DepthObservation_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::unitree_sim::msg::dds_::DepthObservation_>::type_map_blob_sz() { return 586; }
template<> constexpr unsigned int TopicTraits<::unitree_sim::msg::dds_::DepthObservation_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::unitree_sim::msg::dds_::DepthObservation_>::type_map_blob() {
  static const uint8_t blob[] = {
 0xc0,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xd6,  0xb6,  0x8d,  0x24,  0xe9,  0x72,  0xf2, 
 0x9b,  0xbf,  0x17,  0x53,  0x17,  0x69,  0x96,  0x00,  0xa8,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x98,  0x00,  0x00,  0x00,  0x09,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0xdc,  0xdf,  0xb6,  0x26,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x0a,  0xbf,  0x98,  0xfd,  0x35,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x4b,  0xb3,  0x9c,  0x5c, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0xea,  0xae,  0x26,  0xa6,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0xb4,  0x35,  0xe2,  0x27,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x84,  0xbe,  0xa1,  0xf0, 
 0x0b,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x38,  0xe4,  0xa1,  0x61,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x1c,  0xbc,  0x46,  0x4b,  0x00, 
 0x10,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00,  0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09, 
 0x8d,  0x77,  0x7f,  0x38,  0x5b,  0x01,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x74,  0x10,  0x72, 
 0x5b,  0x83,  0x4a,  0x41,  0xe9,  0x8c,  0xa5,  0x61,  0x29,  0x38,  0x65,  0x00,  0x43,  0x01,  0x00,  0x00, 
 0xf2,  0x51,  0x01,  0x00,  0x32,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2a,  0x00,  0x00,  0x00, 
 0x75,  0x6e,  0x69,  0x74,  0x72,  0x65,  0x65,  0x5f,  0x73,  0x69,  0x6d,  0x3a,  0x3a,  0x6d,  0x73,  0x67, 
 0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x44,  0x65,  0x70,  0x74,  0x68,  0x4f,  0x62,  0x73, 
 0x65,  0x72,  0x76,  0x61,  0x74,  0x69,  0x6f,  0x6e,  0x5f,  0x00,  0x00,  0x00,  0x03,  0x01,  0x00,  0x00, 
 0x09,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x08,  0x00, 
 0x0f,  0x00,  0x00,  0x00,  0x66,  0x72,  0x61,  0x6d,  0x65,  0x5f,  0x73,  0x65,  0x71,  0x75,  0x65,  0x6e, 
 0x63,  0x65,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x0a,  0x00,  0x09,  0x00,  0x00,  0x00,  0x73,  0x69,  0x6d,  0x5f,  0x74,  0x69,  0x6d,  0x65, 
 0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00, 
 0x09,  0x00,  0x00,  0x00,  0x66,  0x72,  0x61,  0x6d,  0x65,  0x5f,  0x69,  0x64,  0x00,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x77,  0x69,  0x64,  0x74,  0x68,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0x00,  0x07,  0x00,  0x00,  0x00,  0x68,  0x65,  0x69,  0x67,  0x68,  0x74,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00, 
 0x09,  0x00,  0x00,  0x00,  0x65,  0x6e,  0x63,  0x6f,  0x64,  0x69,  0x6e,  0x67,  0x00,  0x00,  0x00,  0x00, 
 0x18,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x0a,  0x00,  0x00,  0x00, 
 0x6e,  0x65,  0x61,  0x72,  0x5f,  0x63,  0x6c,  0x69,  0x70,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00, 
 0x07,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x09,  0x00,  0x00,  0x00,  0x66,  0x61,  0x72,  0x5f, 
 0x63,  0x6c,  0x69,  0x70,  0x00,  0x00,  0x00,  0x00,  0x17,  0x00,  0x00,  0x00,  0x08,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x80,  0xf3,  0x01,  0x00,  0x00,  0x09,  0x05,  0x00,  0x00,  0x00,  0x64,  0x61,  0x74,  0x61, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x74,  0x10,  0x72, 
 0x5b,  0x83,  0x4a,  0x41,  0xe9,  0x8c,  0xa5,  0x61,  0x29,  0x38,  0x65,  0xf1,  0xd6,  0xb6,  0x8d,  0x24, 
 0xe9,  0x72,  0xf2,  0x9b,  0xbf,  0x17,  0x53,  0x17,  0x69,  0x96, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::unitree_sim::msg::dds_::DepthObservation_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xd6,  0xb6,  0x8d,  0x24,  0xe9,  0x72,  0xf2,  0x9b,  0xbf,  0x17,  0x53, 
 0x17,  0x69,  0x96,  0x00,  0xac,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x74,  0x10,  0x72,  0x5b,  0x83,  0x4a,  0x41,  0xe9,  0x8c,  0xa5,  0x61, 
 0x29,  0x38,  0x65,  0x00,  0x47,  0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::unitree_sim::msg::dds_::DepthObservation_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::unitree_sim::msg::dds_::DepthObservation_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::unitree_sim::msg::dds_::DepthObservation_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::unitree_sim::msg::dds_::DepthObservation_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::unitree_sim::msg::dds_::DepthObservation_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.frame_sequence()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.sim_time()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.frame_id(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.width()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.height()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.near_clip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.far_clip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!write(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !write(streamer, instance.data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::unitree_sim::msg::dds_::DepthObservation_& instance, bool as_key) {
  auto &props = get_type_props<::unitree_sim::msg::dds_::DepthObservation_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::unitree_sim::msg::dds_::DepthObservation_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.frame_sequence()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.sim_time()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.frame_id(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.width()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.height()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.near_clip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.far_clip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!read(streamer, se_1))
        return false;
      instance.data().resize(se_1);
      if (se_1 > 0 &&
          !read(streamer, instance.data()[0], se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::unitree_sim::msg::dds_::DepthObservation_& instance, bool as_key) {
  auto &props = get_type_props<::unitree_sim::msg::dds_::DepthObservation_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::unitree_sim::msg::dds_::DepthObservation_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.frame_sequence()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.sim_time()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.frame_id(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.width()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.height()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.near_clip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.far_clip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = uint32_t(instance.data().size());
      if (!move(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !move(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::unitree_sim::msg::dds_::DepthObservation_& instance, bool as_key) {
  auto &props = get_type_props<::unitree_sim::msg::dds_::DepthObservation_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::unitree_sim::msg::dds_::DepthObservation_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.frame_sequence()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.sim_time()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.frame_id(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.width()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.height()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.encoding(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 6:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.near_clip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 7:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.far_clip()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 8:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(false, true))
        return false;
      {
      uint32_t se_1 = 0;
      if (!max(streamer, se_1))
        return false;
      if (se_1 > 0 &&
          !max(streamer, float(), se_1))
        return false;
      }  //end sequence 1
      if (!streamer.finish_consecutive())
        return false;
      streamer.position(SIZE_MAX);
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::unitree_sim::msg::dds_::DepthObservation_& instance, bool as_key) {
  auto &props = get_type_props<::unitree_sim::msg::dds_::DepthObservation_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_DEPTHOBSERVATION__HPP
